apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: auth
          imagePullPolicy: Never
          env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: NODE_ENV
            - name: JWT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: JWT_PRIVATE_KEY
            - name: JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: JWT_PUBLIC_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3001
      targetPort: 3001
