apiVersion: apps/v1
kind: Deployment
metadata:
  name: junk-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: junk
  template:
    metadata:
      labels:
        app: junk
    spec:
      containers:
        - name: junk
          image: junkit-junk
          imagePullPolicy: Never
          env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: NODE_ENV
            - name: JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: JWT_PUBLIC_KEY
            - name: MONGO_URI
              value: "mongodb://junk-mongo-service:27017/junk"
            - name: NATS_URL
              value: "http://nats-service:4222"
            - name: NATS_CLUSTER_ID
              value: "junk-it"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: junk-service
spec:
  selector:
    app: junk
  ports:
    - name: junk
      protocol: TCP
      port: 3001
      targetPort: 3001
