apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: orders
          imagePullPolicy: Never
          env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: NODE_ENV
            - name: JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: JWT_PUBLIC_KEY
            - name: MONGO_URI
              value: "mongodb://orders-mongo-service:27017/orders"
            - name: NATS_URL
              value: "http://nats-service:4222"
            - name: NATS_CLUSTER_ID
              value: "junk-it"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: EXPIRATION_WINDOW_SECONDS
              value: "900"
---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
spec:
  selector:
    app: orders
  ports:
    - name: orders
      protocol: TCP
      port: 3001
      targetPort: 3001
